### PR TITLE
Rebase on 3.4 and limited support for wine-devel

### PR DESCRIPTION
**Pull request by Firerat**
https://github.com/acomminos/wine-pba/issues/42#issue-308024879

split patching wined3d-csmt/Makefile.in off to 1st patch
those wishing to patch devel simply ignore 1st patch

### CODE REVIEW

**Comment by Firerat** [comment]
Think I might just point people in a better direction
like a simple script
```
PatchDir=../wine-pba/patches
[[ -d dlls/wined3d-csmt ]] \
    || git am -3 < <(sed '/csmt/,/device/d' ${PatchDir}/*.patch) \
    && git am -3 ${PatchDir}/*.patch
```
https://github.com/acomminos/wine-pba/issues/42#issue-308024879
but not had much luck convincing people of the merits of git's apply patches from mailbox with 3 way merge

**Comment by goldpaw** [comment]
Trying to read up on the 3way thing a bit here. If my old brain isn't completely old, it basically means that instead of patching a source file with first patch A then patch B, it compares the source to both A and B at once and apply all the changes, right? 

Meaning if somebody added "mouse" to a database, and another patch adds "moose", and they are both applied as "normal" patches assuming the source is unchanged, only the last applied would actually be applied since one would potentially overwrite the other, while the 3way merge would detect that 2 things had been added, and add both? 

If that's the logic, then yes, I think the rest of us need to look more into it. It would really remove some of the usual problems we encounter when applying several patchsets to the same source. Especially when one of the patchsets (wine-staging) has a habit of changing fairly often.

**Comment by Valmar33** [comment]
This is the best article I've seen on how a Git three-way merge works:

http://www.drdobbs.com/tools/three-way-merging-a-look-under-the-hood/240164902

**Comment by Valmar33** [comment]
Also, the three-way merge was automatic for vanilla 3.4, bar having to manually deal with the wined3d-csmt chunk.

**Pull request closed without merging**
