### PR TITLE
Update Wine version in README to 3.5

### PR DESCRIPTION
**Pull request by SleepProgger**
Because it would have saved me some time if the README would have been up to date and PR #55, why ever, mixed  two different things,

*Shortest PR i ever did*

### CODE REVIEW

**Comment by Firerat** [comment]
true, but a quick look at `git log` would have told you the patchset was targeting 3.5. Who invests time without reading the commit history first?

tbh, imo version in the readne should be replaced with a reference to tags, or to refer to commit history

it was days between my initial fix readme commit and the extras I pushed later at someone elses request.
I could have rebranched and created a new pr for the extras.
If my extras patchset had been rejected, I expect versioning in readme would have been fixed regardless, which is why I didn't, and still don't, see it as a problem.
I guess I see why you don't see it that way, given the fact you invested time without looking at the commit history.

Anyway, @FireBurn has a new PR for 3.6, this time it includes the readme

**Comment by SleepProgger** [comment]
:+1: for version tags.

Nevertheless an up to date README is always nice, regardless of how easy it is to find the required information by browsing issues/PRs

If the 3.6 PR is going to be accepted, ofc feel free to ignore this PR.

**Comment by Firerat** [comment]
yeap,  
https://github.com/acomminos/wine-pba/issues/25
it just a versioned readme is too easy to miss when updating ( as with the current 3.5 ) and no version eliminates the confusion you had ( version not in readme forces you to seek versiin hints elsewhere )
I didn't mean browse issues/prs .. just the `git log`,  although I do see you would not have that history if using gitgub's download zip feature, 

anyway, I do hope one of the 3.6 PRs would get commited soon,`

I may just close my knobs_and_switches PR soon, I plan to learn more C next week, I want to explore a more dynamic approach to the heap sizes.. i.e. start low and grow
from the limited feedback ( inital geo_cb envvar patch ) I've had very large heap sizes degrade performance,  I belive this is due to coalescing a larger heap size, so I want to increase the heap only when coalesce has not freed anything.

I think initially I may just put a crude counter in device.c , since I noticed heap is reinitalised when alt-tabing , then (this is where learning c comes in ) move that logic into buffer_heap.c's wined3d_buffer_heap_alloc() 

maybe later, inject the learnt heap-size into gane specific pba reg. key ,, so as to avoid any initial stuttering 
obviously have some sane max limits, 
probably going to take more than a week, I don't know C ( tbh I don't know any prog lang)

**Comment by SleepProgger** [comment]
Since #58 is now accepted i am closing this one.

**Pull request closed without merging**
