### PR TITLE
Draft of patches rebased against wine-stable

### PR DESCRIPTION
**Pull request by Xaenalt**
Here's a quick draft (that hopefully I did right, completely not sure how to do this patch format in git) of a version that can also go against wine-stable. It compiled, but I got an error trying to boot WoW on wine-stable. I was able to get other games like FFXIV and GW2 to work though. Let me know how these look, comments/etc

I was thinking of making this request to be a separate branch, but I couldn't find a switch to make the pull request do that

### CODE REVIEW

**Comment by mrdeathjr28** [comment]
Thanks

For now patches apply without troubles, compiling now

**Comment by mrdeathjr28** [comment]
Build compiled correctly

**Comment by Xaenalt** [comment]
Yay :D Glad that wasn't just my box

**Comment by Xaenalt** [comment]
Also, I wasn't really sure how to do a git format-patch to preserve the original author name, I feel like I should put that back in since I really didn't do a whole lot to rebase it onto wine-stable

**Comment by acomminos** [comment]
Thanks for posting this. I'm going to see if I can make a shared patch series for vanilla wine and wine staging, such that the bulk of the code can apply cleanly to both cases (with version-specific harnesses).

**Comment by Xaenalt** [comment]
That's awesome :D the only parts that didn't apply cleanly (with a warning about offsets) were the ones like this:

```
static const struct wined3d_resource_ops buffer_resource_ops =
{
    buffer_resource_incref,
    buffer_resource_decref,
    buffer_resource_preload,
    buffer_unload,
    buffer_resource_sub_resource_map,
    buffer_resource_sub_resource_map_info,
    buffer_resource_sub_resource_map_cs,
    buffer_resource_sub_resource_unmap,
    buffer_resource_sub_resource_unmap_cs,
};
```

where it had an issue with `buffer_resource_sub_resource_map_info` being after `buffer_resource_sub_resource_map`. By editing that part out, it applied just fine

**Comment by mrdeathjr28** [comment]
At simple is very impressive with age of mythologies extended edition in last video with wine 3.3

https://youtu.be/KUD5lY8SUMI?t=1h39m25s

In this moment stay around 48fps

And this screens in same scene* with same camera position** with pba give around 70fps (in both camera modes: closer and far) also with recording (nvenc used)

*stay in day, in video stay in night but day is impact fps more

**far camera impact fps in vanilla

Closer Camera

https://imgur.com/iaw9P1A

Far Camera

https://imgur.com/U2ZYjR2

And cpu use seems lower

**Comment by Xaenalt** [comment]
After attempting some commit reordering, these can be applied on top of staging, (with the offset warnings) provided one skips applying `d3d11-Deferred_Context`, which has dependencies on `wined3d-CSMT_Helper` and `wined3d-CSMT_Main`

Those sound like they might be necessary for some other performance gains

**Comment by mrdeathjr28** [comment]
In kane and lynch 2 appears curious effect

With regular csmt in second chapter begin around 50fps and 39% of gpu use but with csmt+pba begins at 40 to 45fps but with around 90% of gpu use

**Comment by Xaenalt** [comment]
Updated with today's changes to WINE and your patches, also cleaned up the email header bits, everything still compiled successfully

**Comment by mrdeathjr28** [comment]
I finish some tests between wine 3.3 vanilla and wine 3.3 + PBA

Age of Mythologies Extended Edition

Vanilla

https://www.youtube.com/watch?v=KUD5lY8SUMI

Vanilla + PBA

https://www.youtube.com/watch?v=eHBLkQ0dHdg

Need for Speed Hot Pursuit 2010

Vanilla

https://www.youtube.com/watch?v=YJjzE27RCZY

Vanilla + PBA

https://www.youtube.com/watch?v=E8vSNwivFKM

In both cases performance improve so much, around 20 to 25fps in each game

**Comment by mrdeathjr28** [comment]
Compiled you updates patches without troubles

And test bombshell, in this titles dont change much maybe 5 or 8 fps more

But in dishonored is huge update pass to 35 - 40fps to 55 to 60fps

**Comment by mrdeathjr28** [comment]
Another interesting case is remember me

Vanilla

https://i.imgur.com/KOCIo7Y.jpg

Vanilla + PBA

https://i.imgur.com/KjnLJq6.jpg

**Comment by smirgol** [comment]
Fallout 4

In my test scenario (sanctuary, standing at end of bridge and looking towards the town, pointing at the cooking station), my framerate improves from 9fps (staging only) to 23fps (staging + pba). Vanilla is at about 7fps.

radeontop shows a gpu utilization of 25% to 28% max
cpu is at ~360% (out of 800%)

To say, there seem to be even more bottlenecks somewhere, as neither GPU nor CPU are maxed out. But the pba patches are a huge improvement already!

AMD R290X
AMD FX(tm)-8350 Eight-Core Processor
Mesa 18.1.0-devel - padoka PPA 
Ubuntu 17.10
Fallout4: 1080p at lowest settings possible.

**Comment by mrdeathjr28** [comment]
Another case is dishonored

Vanilla

https://imgur.com/UAnBTFQ

Vanilla + PBA

https://imgur.com/RIMwGIp

**Comment by mrdeathjr28** [comment]
Blur

Vanilla

https://imgur.com/Je05B82

Vanilla + PBA

https://imgur.com/C1wwMDQ

**Comment by Xaenalt** [comment]
@smirgol I think the wine CSMT maxes out around 360%, at least I haven't seen many games take up more cpu than that. It would be really interesting to see a slice of perf from around that time to possibly identify the issue further. I lack a copy of Fallout 4 though.

If possible, can you run your game with the patched suite by prepending it with `perf record`. Something like
```
perf record wine fallout4.exe
```
And playing for a bit to get a good sample. It should create a file `perf.data` in the local directory. That file can be browsed with `perf report -i perf.data`

**Comment by smirgol** [comment]
@Xaenalt Is this of help, or would you need the full perf.log (~110M)?
[https://pastebin.com/zHT0Cg6e](url) (cannot attach the file somehow)

**Comment by mrdeathjr28** [comment]
Batman Arkham Asylum

Vanilla

https://imgur.com/oFsd97p

Vanilla + PBA

https://imgur.com/bYb8Kx7

**Comment by mrdeathjr28** [comment]
Hydrophobia Propecy

This game have troubles and with vanilla runs around 20fps in menus and 25fps in game

But PBA improve performance so much

Vanilla + PBA

https://imgur.com/uITmWdh

https://imgur.com/8kBL4dg

Vanilla + PBA + CSMT

https://imgur.com/8qmxZim

https://imgur.com/VEdxFGw

**Comment by mrdeathjr28** [comment]
Skyrim + Mods

Vanilla + PBA

https://imgur.com/CFHLL3m

Vanilla + PBA + CSMT

https://imgur.com/bF1SS7w

**Comment by Xaenalt** [comment]
@smirgol That's great data!

**Comment by mrdeathjr28** [comment]
Sonic All Stars Racing Transformed

This title with vanilla dont give more 30 to 35fps

But now with PBA

https://imgur.com/KSpEg0K

https://imgur.com/G6IiPYI

https://imgur.com/u4lFSmG

Curiously added CSMT + PBA give very similar fps

**Comment by IngeniousDox** [comment]
This testing you are doing is leaving me with 3 questions.

- Does PBA do anything when CSMT is disabled? I thought it only worked when it was enabled.
- How different is Vanilla CSMT compared to Staging CSMT?
- Howmany scenarios do we end up with if it is different?

With only vanilla Wine 3.3 Scenarios:
1. Wine 3.3 with vanilla CSMT (Enabled by default now)
2. Wine 3.3 without CSMT (Disabling CSMT using the dword registery key)
3. Wine 3.3 with vanilla CSMT + PBA
4. Wine 3.3 without CSMT + PBA

Wine Staging adds Staging CSMT as another option. It loads a different wined3d dll when enabled. You can then test with Staging CSMT, with Vanilla CSMT, or without CSMT completely, and then all those options with PBA. Thats a lot of different testing scenarios. Or does PBA for Staging 3.3 only apply to Staging CSMT and not the vanilla counterpart?

Right now I'm only testing WoW, and it doesn't work with vanilla Wine 3.3, so not many options to test, but already thinking ahead.

**Comment by mrdeathjr28** [comment]
Test Drive Ferrari Legends

This game in vanilla give around in same scene 30fps and with csmt around 45fps

Vanilla + PBA

https://imgur.com/3JezD0f

https://imgur.com/4MaIgIK

Vanilla + PBA + CSMT

https://imgur.com/MuyiIeK

https://imgur.com/85qdcfp

**Comment by mrdeathjr28** [comment]
> This testing you are doing is leaving me with 3 questions.
> 
> Does PBA do anything when CSMT is disabled? I thought it only worked when it was enabled.
> How different is Vanilla CSMT compared to Staging CSMT?
> Howmany scenarios do we end up with if it is different?
> With only vanilla Wine 3.3 Scenarios:
> 
> Wine 3.3 with vanilla CSMT (Enabled by default now)
> Wine 3.3 without CSMT (Disabling CSMT using the dword registery key)
> Wine 3.3 with vanilla CSMT + PBA
> Wine 3.3 without CSMT + PBA
> Wine Staging adds Staging CSMT as another option. It loads a different wined3d dll when enabled. You can then test with Staging CSMT, with Vanilla CSMT, or without CSMT completely, and then all those options with PBA. Thats a lot of different testing scenarios. Or does PBA for Staging 3.3 only apply to Staging CSMT and not the vanilla counterpart?
> 
> Right now I'm only testing WoW, and it doesn't work with vanilla Wine 3.3, so not many options to test, but already thinking ahead.

Hi

Yeah PBA without csmt give improvement case batman arkham city, hydrophobia and maybe others, At simple seek reduce cpu use

However in other cases when is used with csmt improve so much case dishonored, hydrophobia and others

But in some cases pba + csmt dont have effect case sonic all stars racing transformed or hurt fps case batman arkam city

Vanilla CSMT implementation in my tests is stable in long times, before because staging have more patches for other things

My wine have CSMT disabled as default because benefit in some apps but in others not

Respect CSMT registry entry, i use donat enikeev csmt patch*

https://mega.nz/#!XNkBVDgA!nhjqiDlzfxw7VhY8OVTpNXzZtYmoLZm6wNVkfX6ueZs

*This patch shows csmt in winecfg and allow configure per app, for disgrace henri verbeet dont approve this patch

:)

**Comment by mrdeathjr28** [comment]
Call of Juarez Gunslinger

Vanilla + PBA

https://imgur.com/6suCGr0

https://imgur.com/3DCGAjj

https://imgur.com/7HxXsUy

Vanilla + PBA + CSMT

https://imgur.com/ko2czdZ

https://imgur.com/qW2dz7T

https://imgur.com/ySYFBHK

**Comment by mrdeathjr28** [comment]
If any one interested, this is my wine 3.3 vanilla i386 + pba + donat enikeev csmt patch in deb package

https://mega.nz/#!nY0wgQQC!iRnIeVxWMmpFj0vCIiWnEsRqf3zzaIa5mwOZaJ9do7c

:)

**Comment by mrdeathjr28** [comment]
Legendary

Vanilla + PBA

https://imgur.com/13iR859

Vanilla + PBA + CSMT

https://imgur.com/QU3Tua3

**Comment by mrdeathjr28** [comment]
Deus Ex Human Revolution

Vanilla + PBA

https://imgur.com/u7HXQLJ

https://imgur.com/4YwWoso

Vanilla + PBA + CSMT

https://imgur.com/RpUyDUn

https://imgur.com/jdBYoSN

**Comment by mrdeathjr28** [comment]
Lili Child of Geos

Vanilla + PBA

https://imgur.com/C5vcoLH

Vanilla + PBA + CSMT

https://imgur.com/QPZ2ShO

**Comment by mrdeathjr28** [comment]
Contrast

Vanilla + PBA

https://imgur.com/QaA75qH

Vanilla + PBA + CSMT

https://imgur.com/laKtQ62

**Comment by mrdeathjr28** [comment]
Borderlands 1

Vanilla + PBA

https://imgur.com/vCPO0Qc

Curiously PBA + CSMT hurt fps around 10fps

**Comment by mrdeathjr28** [comment]
Homefront

Vanilla + PBA

https://imgur.com/1EBzBjq

Vanilla + PBA + CSMT

https://imgur.com/EY3VybM

**Comment by mrdeathjr28** [comment]
Fable Anniversary

Vanilla + PBA

https://imgur.com/64ghlLc

Vanilla + PBA + CSMT

https://imgur.com/T9ySCtc

**Comment by mrdeathjr28** [comment]
Front Mission Evolved

Vanilla + PBA

https://imgur.com/7sZz1Ia

Vanilla + PBA + CSMT

https://imgur.com/Z04yyF7

**Comment by mrdeathjr28** [comment]
Dragon Dogma

Vanilla + PBA

https://imgur.com/pdDeYVE

https://imgur.com/px8rbDq

Vanilla + PBA + CSMT

https://imgur.com/phjYalq

https://imgur.com/J8IqpKF

**Comment by mrdeathjr28** [comment]
Enslaved

Vanilla + PBA

https://imgur.com/Z3zcVgc

Vanilla + PBA + CSMT

https://imgur.com/MeZ4hoO

**Comment by mrdeathjr28** [comment]
Battlefield Bad Company 2

Vanilla + PBA

https://imgur.com/GAKlqIo

Vanilla + PBA + CSMT

https://imgur.com/heMOM4v

**Comment by mrdeathjr28** [comment]
Hunted Hells Reach

Vanilla + PBA

https://imgur.com/R3pHePF

Vanilla + PBA + CSMT

https://imgur.com/9ZX1Brh

**Comment by mrdeathjr28** [comment]
Crysis

Vanilla + PBA

https://imgur.com/w9ubHsq

Vanilla + PBA + CSMT

https://imgur.com/WvRiBqQ

**Comment by mrdeathjr28** [comment]
Aliens Colonial Marines

Vanilla + PBA

https://imgur.com/5Ux03Pf

Vanilla + PBA + CSMT

https://imgur.com/te6BzKz

**Comment by mrdeathjr28** [comment]
Red Faction Guerilla

Vanilla + PBA

https://imgur.com/S3pmAYA

Vanilla + PBA + CSMT

https://imgur.com/B0qZd7U

**Comment by mrdeathjr28** [comment]
New patchs compile correctly but various games crash with this patchs case aliens colonial marines, mirrors egde , remember me and others

**Pull request closed without merging**
