### PR TITLE
README.md: update base to wine-staging 3.5

### PR DESCRIPTION
**Pull request by Firerat**
Closes (#54)

### CODE REVIEW

**Comment by Firerat** [comment]
nearly forgot, added knobs and switches, helping users to break performance ;)
on the serious side.. stops FF XIV 32bit dx9 client crash when geo and cb heap sizes are reduced. so not all bad

**Comment by IngeniousDox** [comment]
You should probably have made this 2 pull requests, instead of shoving this other change into the simple README fix PR. (Github doesn't mind if you use a lot, keep it clean).

**Comment by Firerat** [comment]
yeah, I made it worse now ;)
I should have closed first, and squashed

**Comment by Firerat** [comment]
true, 
tbh the version dosn't need to be in the README,
tags should be enough
anyway, kind of moot in this case.., these are just patches, the README never gets into Andrew's real wine repo

**Comment by IngeniousDox** [comment]
Then you are not understanding how pull requests work. If he accepts this full PR, the README commit is accepted aswell. So if he doesn't want that, you are forcing him to manually cherry pick parts of your PR. This is just evil, and most repo will reject badly formatted PRs even if the code is good.

You should reopen this 1 with just the README change, and remove the README change from the other 1. I know the README change is trivial, but it is just good practice.

**Comment by Firerat** [comment]
I'm usually quite pedantic , but in this case.. it really isn't worth it.

**Pull request closed without merging**
